---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: true

platforms:
- name: centos-5.11
- name: centos-6.6
- name: centos-7.0
- name: debian-6.0.10
- name: debian-7.7
- name: fedora-19
- name: fedora-20
- name: freebsd-9.2
- name: freebsd-10.0
- name: opensuse-13.1-x86_64
- name: ubuntu-10.04
- name: ubuntu-12.04
- name: ubuntu-14.04
- name: ubuntu-14.10

suites:
- name: default
  run_list:
  - recipe[ssh_authorized_keys_test::default]
